#define CREATE_STACK(NAME, MAX_SIZE, TYPE) \
unsigned int __ARRAY_STACK_##NAME##_TOTAL_SIZE = MAX_SIZE, __ARRAY_STACK_##NAME##_SIZE=0; \
TYPE __ARRAY_STACK_##NAME##_ARRAY[MAX_SIZE];

#define EXTERN_STACK(NAME, MAX_SIZE, TYPE) \
extern unsigned int __ARRAY_STACK_##NAME##_TOTAL_SIZE, __ARRAY_STACK_##NAME##_SIZE; \
extern TYPE __ARRAY_STACK_##NAME##_ARRAY[MAX_SIZE];

#define INSERT_STACK(NAME, VALUE) \
if(__ARRAY_STACK_##NAME##_SIZE < __ARRAY_STACK_##NAME##_TOTAL_SIZE ) \
	__ARRAY_STACK_##NAME##_ARRAY[__ARRAY_STACK_##NAME##_SIZE++] = VALUE;

#define POP_STACK(NAME) __ARRAY_STACK_##NAME##_ARRAY[--__ARRAY_STACK_##NAME##_SIZE]
#define SIZE_STACK(NAME) __ARRAY_STACK_##NAME##_SIZE
#define MAX_SIZE_STACK(NAME) __ARRAY_STACK_##NAME##_TOTAL_SIZE
